name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.0
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        # Username do Docker Hub
        username: ${{ secrets.DOCKERHUB_USER }}
        # Senha do Docker Hub
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          mattheusva/kube-news:${{ github.run_number }}
          mattheusva/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.0

      
    
