name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        # Username do Docker Hub
        username: ${{ secrets.DOCKERHUB_USER }}
        # Senha do Docker Hub
        password: ${{ secrets.DOCKERHUB_PWD }}
    
    
